<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CourseNet.Academic.Adapter.Driving.Api</RootNamespace>
    <UserSecretsId>ed08a311-94ca-4e02-a1e2-45fb2ad5e527</UserSecretsId>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\CourseNet.Academic.Core\CourseNet.Academic.Core.csproj" />
    <ProjectReference Include="..\..\Driven\CourseNet.Academic.Adapter.Driven.Persistence\CourseNet.Academic.Adapter.Driven.Persistence.csproj" />
    <ProjectReference Include="..\..\Driven\CourseNet.Academic.Adapter.Driven.Auth\CourseNet.Academic.Adapter.Driven.Auth.csproj" />
  </ItemGroup>

</Project>
